### ISSUE TITLE
Figure out why Travis build is failing

### ISSUE THREAD

**Issue by tylergaw** [tylergaw/ember-cli-chartist#10]
Do that and then fix it.

**Comment by tylergaw** [comment]
Not sure what the hell the problem is, the unit tests aren't failing, they aren't running. It's getting JS errors. https://travis-ci.org/tylergaw/ember-cli-chartist/builds/48284811#L292 buncha nonsense, dangit

**Comment by rzane** [comment]
Just realized all of my tests started failing by using this. The problem is that phantomjs uses an older version of webkit that doesn't support Function.prototype.bind.

A polyfill should fix it right up.

**Comment by tylergaw** [comment]
@DarrenN fixed this in https://github.com/tylergaw/ember-cli-chartist/pull/28 will be getting that merged in and a new release out soon

**Comment by rzane** [comment]
:+1:
