### ISSUE TITLE
Error with chart component

### ISSUE THREAD

**Issue by Globegitter** [tylergaw/ember-cli-chartist#24]
First of all thanks for this plugin - really useful.

I am using ember-cli 0.2.0-beta.1 with the POD structure and trying to make my own chart-component. So I have `app/components/topic-funds-over-time/component.js` as well as the `template.hbs` in the same folder.

My code is just:

```js
import ChartistChart from '../chartist-chart';

export default ChartistChart.extend({
  type: 'bar',
  welcome: function() {
    console.log('Hello component');
    var data = this.get('testData');
    this.set('data', data);
  }.on('init'),
  testData: function() {
    return {
      chartData: {
        labels: ['Day1', 'Day2', 'Day3'],
        series: [
          [5, 4, 8],
          [10, 2, 7],
          [8, 3, 6]
        ]
      }
    };
  }.property()
```

and I am getting the follwing error:
```
Uncaught TypeError: Cannot read property 'update' of undefined chartist-chart.js:60 (anonymous function)
```

On master branch this is the following line: https://github.com/tylergaw/ember-cli-chartist/blob/master/app/components/chartist-chart.js#L65

Any idea what the issue could be?

Btw, displaying the pre-defined charts such as `{{chartist-chart data=model.chartData}}` works fine.

**Comment by Globegitter** [comment]
Ahhh I assume the issue is `.on('init')`, because the chart only gets defined `.on('didInsertElement')`. I assume this is something that has to be done out of DOM/rendering reasons, right?

**Comment by Globegitter** [comment]
Just played around with it and if I am already sending data to the component, the only way I get it to work is if I have a function that `.observes('chart')`.

I wonder if this could be improved a bit. Even `.on('didInsertElement')` does not work.

Also it might be good if the component itself could check that the chart exists before trying to update.

Anyway, just a couple of observations and if I do get time at some point I'll try to do a PR :)

**Comment by tylergaw** [comment]
Hey @Globegitter sorry for the slow response, been away. Thanks for the report. I'll check this out soon. Yep, PRs are always welcome and appreciated.

**Comment by jherdman** [comment]
@Globegitter are you still having trouble with this? We recently did a bit of an overhaul in the 1.0 version of this plugin.

**Comment by jherdman** [comment]
I'm going to close this issue for now. Please feel free to reopen this issue should it become of interest to you again.
