### ISSUE TITLE
Getting chartist dynamically

### ISSUE THREAD

**Issue by Globegitter** [tylergaw/ember-cli-chartist#25]
As I can see it right now, you are having chartist fixed in the `/vendor/` folder right? How about getting it more dynamically via `addBowerPackageToProject`? See: https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L805 

This would add it to the user's bower.json and therefore could be updated easier.

**Comment by tylergaw** [comment]
Yep, totally. I've been manually copying the files in, pretty bogus. I didn't know about `addBowerPackageToProject`, looks spot on.
