### ISSUE TITLE
Get ember-cli-chartist working with Ember CLI 0.2.x

### ISSUE THREAD

**Issue by misteroneill** [tylergaw/ember-cli-chartist#27]
If you're a developer who needs to run ember-cli-chartist with Ember CLI 0.2.x, put the following in your `config/environment.js` file:

```javascript
ENV.sassOptions = {
  includePaths: [
    'node_modules/ember-cli-chartist/vendor/chartist/scss'
  ]
};
```

Of course, if this array already exists (for example, to get ember-cli-bootstrap-sass working), that string should be added to the `includePaths` array.

**Comment by jherdman** [comment]
#46 should resolve this.
