### ISSUE TITLE
Is there any option to add axis 'title' in ember chartist?? 

### ISSUE THREAD

**Issue by santosh1994** [tylergaw/ember-cli-chartist#35]
@tylergaw

**Comment by jherdman** [comment]
Hey @santosh1994 . It looks like you'll need to use the https://gionkunz.github.io/chartist-js/plugins.html#axis-title-plugin plugin. Unfortunately our plugin story isn't very complete yet (see #31). If you're interested we'd love to have you help flesh out our plugin story.
