### ISSUE TITLE
Update to 0.9.1

### ISSUE THREAD

**Issue by marcemira** [tylergaw/ember-cli-chartist#41]
Hey there is a 0.9.1 version. Is it possible to update? tried to use lastest but it throws somethig like:
`Uncaught Error: Exceeded maximum number of iterations while optimizing scale step!`
Thanks!

**Comment by tylergaw** [comment]
@marcemira I have a PR in progress for it right now https://github.com/tylergaw/ember-cli-chartist/pull/39 though it's giving me a fair amount of trouble, so I'm not sure when I'll be able to finish it.

**Comment by marcemira** [comment]
:+1:  Thanks @tylergaw, I'll be glad to help

**Comment by jherdman** [comment]
I'm rebooting the effort in #47, @marcemira. Do you have a production app you could try this change with?

**Comment by marcemira** [comment]
@jherdman nope, end up removing it :confused:

**Comment by jherdman** [comment]
Aw snap! Sorry to hear that.
