### ISSUE TITLE
I love Chartist but it looks like repo is not being kept up.

### ISSUE THREAD

**Issue by brendanoh** [tylergaw/ember-cli-chartist#45]
I love Chartist but it looks like repo is not being kept up.

Is anyone still using this?

**Comment by tylergaw** [comment]
Hey @brendanoh yeah, between the day-to-day and life stuffs I've not had the bandwidth to give the project attention. The last thing I was working on was getting upgraded to Chartist 0.9.x in https://github.com/tylergaw/ember-cli-chartist/pull/39 I was running into trouble there so I got stalled.

Totally open to PRs if you see things you want to go after.

**Comment by mohlek** [comment]
I contacted the chartist guys and opened an issue due to the empty dataset bug. They fixed it recently.
Hope to see a working version soon :)

**Comment by jherdman** [comment]
Hey team. Is it safe to close this issue? Check out #47 if you want to help ensure we've upgraded Chartist correctly.

**Comment by jherdman** [comment]
I'm going to close this issue as 0.9.8 was cut just eight days ago.
